# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/LargeLanguageModels',
                'doc_host': 'https://abdelkareemkobo.github.io',
                'git_url': 'https://github.com/abdelkareemkobo/LargeLanguageModels',
                'lib_path': 'LargeLanguageModels'},
  'syms': {'LargeLanguageModels.core': {'LargeLanguageModels.core.foo': ('core.html#foo', 'LargeLanguageModels/core.py')}}}
